### ISSUE TITLE
Contato com a Prefeitura do Recife

### ISSUE THREAD

**Issue by aplneto** [aplneto/projeto_ES#4]
Entrar em contato com a Prefeitura do Recife ou Secretaria da Saúde. Precisamos de informações sobre o banco de dados ou dos arquivos contendo as informações dos hospitais para compormos nosso próprio banco de dados, caso ainda não haja um.

**Comment by prgs1** [comment]
segundo o cliente, as informações a serem utilizadas no aplicativo (Dados de postos de saúde, e afins) devem ser encontrados no Portal de dados abertos da Prefeitura do Recife (para a saúde pública)

http://dados.recife.pe.gov.br/

**Comment by prgs1** [comment]
http://dados.recife.pe.gov.br/dataset/rede-de-saude-municipal
