### ISSUE TITLE
Fazer protótipo em papel do aplicativo, segundo as necessidades do cliente

### ISSUE THREAD

**Issue by prgs1** [aplneto/projeto_ES#5]
p/ entregar na próxima reunião com o cliente (dia 26/03, às 10:15)

**Comment by aplneto** [comment]
Arquivo criado com a plataforma PencilProject
[Wireframe.zip](https://github.com/aplneto/projeto_ES/files/3000018/Wireframe.zip)

**Comment by aplneto** [comment]
![comentrios](https://user-images.githubusercontent.com/34499237/54964087-df5afd80-4f49-11e9-9f25-b009867a6f22.png)
![comentrios_mobile](https://user-images.githubusercontent.com/34499237/54964088-df5afd80-4f49-11e9-9eab-ce51c3fdf909.png)
![login_browser](https://user-images.githubusercontent.com/34499237/54964089-df5afd80-4f49-11e9-852e-fa8a7080fec1.png)
![mapa](https://user-images.githubusercontent.com/34499237/54964090-dff39400-4f49-11e9-932e-b4a623263da4.png)
![mapa_mobile](https://user-images.githubusercontent.com/34499237/54964091-dff39400-4f49-11e9-83c6-1c38b7b3fa09.png)
![pesquisa](https://user-images.githubusercontent.com/34499237/54964092-dff39400-4f49-11e9-94d7-d961662778f8.png)
![pgina_inicial_browser](https://user-images.githubusercontent.com/34499237/54964093-dff39400-4f49-11e9-9343-c8514a282821.png)
![pgina_inicial_mobile](https://user-images.githubusercontent.com/34499237/54964095-dff39400-4f49-11e9-8e2d-16ee5fe66c4f.png)
![profile_browser](https://user-images.githubusercontent.com/34499237/54964096-e08c2a80-4f49-11e9-9a99-d416b4b28aff.png)
![resultado](https://user-images.githubusercontent.com/34499237/54964097-e08c2a80-4f49-11e9-857b-e0d3a67a1b26.png)

**Comment by aplneto** [comment]
Após a reunião de apresentação, o wireframe do projeto foi aprovado pelo cliente.

**Comment by aplneto** [comment]
Apresentação do wireframe foi bem sucedida ao segundo cliente (Cinthia Vasconcelos). Sugestões do usuário registradas (#13).
